version: 2

jobs:
  build-hello:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build  -t franckart/ornikar-test-hello:$CIRCLE_SHA1 -f cloud-interview/apps/hello/Dockerfile .
      - run:
          name: Login to dockerhub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run:
          name: Push application Docker image
          command: |
             docker push franckart/ornikar-test-hello:$CIRCLE_SHA1

  build-world:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to dockerhub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run:
          name: Build application Docker image
          command: |
            docker build  -t franckart/ornikar-test-world:$CIRCLE_SHA1 -f cloud-interview/apps/world/Dockerfile cloud-interview/apps/world
      - run:
          name: Push application Docker image
          command: |
             docker push franckart/ornikar-test-world:$CIRCLE_SHA1
    
  codefresh-run:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Download and run codefresh
          command: |
            echo "Download and run codefresh"
            apt update  -y
            apt install curl unzip -y
            curl -o "/tmp/"  https://github.com/codefresh-io/cli/releases/download/v0.82.3/codefresh-v0.82.3-win-x64.zip
            cd /tmp/ && unzip /tmp/codefresh-v0.82.3-win-x64.zip
            mv /tmp/codefresh  /usr/local/bin/
            codefresh auth create-context --api-key $CODEFRESH_API_KEY
            codefresh run ornikar-test/ornikar-test -v TAG=$CIRCLE_SHA1

            
   
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-hello
      - build-world:
          requires:
            - build-hello
      - codefresh-run:
          requires:
            - build-hello
            - build-world
