version: 2
jobs:
  build-hello:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build  -t franckart/ornikar-test-hello:$CIRCLE_BUILD_NUM -f cloud-interview/apps/hello/Dockerfile .
      - run:
          name: Login to dockerhub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - run:
          name: Push application Docker image
          command: |
             docker push franckart/ornikar-test-hello:$CIRCLE_BUILD_NUM

  build-world:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build  -t franckart/ornikar-test-world:$CIRCLE_BUILD_NUM -f cloud-interview/apps/world/Dockerfile .
      - run:
          name: Push application Docker image
          command: |
             docker push franckart/ornikar-test-world:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-hello
      - build-world:
          requires:
            - build-hello
